version: 0.2
env:
  variables:
    REPOSITORY_URI: 400054515716.dkr.ecr.us-east-1.amazonaws.com/code_1
  exported-variables:
    - IMAGE_TAG
phases:
  pre_build:
    commands:
      - mvn clean package -DskipTests
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "IMAGE_TAG=$IMAGE_TAG"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Build completed successfully."

artifacts:
  files:
    - ../k8s/*.yaml
