version: 0.2
env:
  variables:
    REPOSITORY_URI: 400054515716.dkr.ecr.us-east-1.amazonaws.com/code_1
  exported-variables:
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client 
      - echo "running maven build"
      - mvn clean package -DskipTests
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Replacing IMAGE_PLACEHOLDER in deployment.yaml..."
      - sed -i "s|IMAGE_PLACEHOLDER|$REPOSITORY_URI:$IMAGE_TAG|g" deployment.yaml
      - echo "Updating kubeconfig for EKS..."
      - aws eks --region us-east-1 update-kubeconfig --name my-cluster
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f deployment.yaml -f service.yaml --validate=false
      - echo "Build and deployment completed successfully."

artifacts:
  files:
    - deployment.yaml
    - service.yaml
